import type { DashboardData, NavItem, Workspace } from '@/types'

export const workspaces: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Pune Metro',
    plan: 'Enterprise',
    avatar: 'PM',
  },
  {
    id: 'ws-2',
    name: 'Bangalore Hub',
    plan: 'Pro',
    avatar: 'BH',
  },
  {
    id: 'ws-3',
    name: 'Mumbai Central',
    plan: 'Pro',
    avatar: 'MC',
  },
]

export const navigation: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/',
    icon: 'LayoutDashboard',
  },
  {
    id: 'properties',
    label: 'Properties',
    href: '/properties',
    icon: 'Building2',
    badge: '16',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    icon: 'BarChart3',
    children: [
      {
        id: 'market-trends',
        label: 'Market Trends',
        href: '/analytics/trends',
        icon: 'TrendingUp',
      },
      {
        id: 'locality-compare',
        label: 'Locality Compare',
        href: '/analytics/localities',
        icon: 'MapPin',
      },
      {
        id: 'sentiment',
        label: 'Sentiment',
        href: '/analytics/sentiment',
        icon: 'MessageSquare',
      },
    ],
  },
  {
    id: 'requirements',
    label: 'Requirements',
    href: '/requirements',
    icon: 'Search',
  },
  {
    id: 'recommendations',
    label: 'Recommendations',
    href: '/recommendations',
    icon: 'Sparkles',
    badge: 'New',
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/reports',
    icon: 'FileText',
  },
  {
    id: 'settings',
    label: 'Settings',
    href: '/settings',
    icon: 'Settings',
  },
]

export const mockDashboardData: DashboardData = {
  kpis: [
    {
      id: 'kpi-1',
      label: 'Total Listings',
      value: '2,847',
      change: 12.4,
      changeLabel: 'vs last month',
      icon: 'Building2',
      trend: 'up',
    },
    {
      id: 'kpi-2',
      label: 'Avg. Price / sqft',
      value: '₹9,240',
      change: 3.2,
      changeLabel: 'vs last month',
      icon: 'IndianRupee',
      trend: 'up',
    },
    {
      id: 'kpi-3',
      label: 'Match Rate',
      value: '87.3%',
      change: -1.8,
      changeLabel: 'vs last week',
      icon: 'Target',
      trend: 'down',
    },
    {
      id: 'kpi-4',
      label: 'Active Users',
      value: '1,284',
      change: 8.6,
      changeLabel: 'vs last month',
      icon: 'Users',
      trend: 'up',
    },
  ],
  revenueChart: [
    { name: 'Jan', value: 4200, secondary: 3800 },
    { name: 'Feb', value: 4800, secondary: 4100 },
    { name: 'Mar', value: 5100, secondary: 4400 },
    { name: 'Apr', value: 4900, secondary: 4600 },
    { name: 'May', value: 5600, secondary: 4800 },
    { name: 'Jun', value: 6200, secondary: 5200 },
    { name: 'Jul', value: 6800, secondary: 5500 },
  ],
  localityChart: [
    { name: 'Hinjewadi', value: 9240 },
    { name: 'Wakad', value: 8750 },
    { name: 'Baner', value: 11200 },
    { name: 'Kharadi', value: 7800 },
    { name: 'Whitefield', value: 9800 },
    { name: 'Electronic City', value: 7200 },
  ],
  distributionChart: [
    { name: 'Ready to Move', value: 42 },
    { name: 'Under Construction', value: 35 },
    { name: 'Resale', value: 23 },
  ],
  activities: [
    {
      id: 'act-1',
      user: 'Priya Sharma',
      avatar: 'PS',
      action: 'analyzed',
      target: '2 BHK in Hinjewadi',
      timestamp: new Date(Date.now() - 5 * 60_000).toISOString(),
      type: 'analysis',
    },
    {
      id: 'act-2',
      user: 'System',
      avatar: 'SI',
      action: 'flagged duplicate',
      target: 'Green Heights — Wakad',
      timestamp: new Date(Date.now() - 18 * 60_000).toISOString(),
      type: 'alert',
    },
    {
      id: 'act-3',
      user: 'Rahul Mehta',
      avatar: 'RM',
      action: 'saved listing',
      target: '3 BHK — Baner',
      timestamp: new Date(Date.now() - 45 * 60_000).toISOString(),
      type: 'listing',
    },
    {
      id: 'act-4',
      user: 'Ananya Patel',
      avatar: 'AP',
      action: 'generated report',
      target: 'Pune Investment Q2',
      timestamp: new Date(Date.now() - 2 * 3_600_000).toISOString(),
      type: 'analysis',
    },
    {
      id: 'act-5',
      user: 'Vikram Singh',
      avatar: 'VS',
      action: 'updated requirement',
      target: 'Whitefield rental search',
      timestamp: new Date(Date.now() - 4 * 3_600_000).toISOString(),
      type: 'user',
    },
  ],
  updates: [
    {
      id: 'upd-1',
      title: 'Hinjewadi price index up 4.2%',
      description: 'Strong demand near IT parks driving premium segment growth.',
      timestamp: new Date(Date.now() - 30 * 60_000).toISOString(),
      category: 'market',
      read: false,
    },
    {
      id: 'upd-2',
      title: '42 new listings ingested',
      description: 'MagicBricks and Housing.com data synced successfully.',
      timestamp: new Date(Date.now() - 2 * 3_600_000).toISOString(),
      category: 'listing',
      read: false,
    },
    {
      id: 'upd-3',
      title: 'Sentiment shift detected — Wakad',
      description: 'Negative themes around traffic congestion increasing.',
      timestamp: new Date(Date.now() - 6 * 3_600_000).toISOString(),
      category: 'insight',
      read: true,
    },
    {
      id: 'upd-4',
      title: 'System maintenance completed',
      description: 'Enrichment pipeline v2.1 deployed with improved dedup.',
      timestamp: new Date(Date.now() - 24 * 3_600_000).toISOString(),
      category: 'system',
      read: true,
    },
  ],
  tasks: [
    {
      id: 'task-1',
      title: 'Review deduplication clusters',
      status: 'in_progress',
      priority: 'high',
      assignee: 'Data Team',
      dueDate: new Date(Date.now() + 2 * 86_400_000).toISOString(),
      progress: 65,
    },
    {
      id: 'task-2',
      title: 'Update sentiment dataset',
      status: 'pending',
      priority: 'medium',
      assignee: 'AI Team',
      dueDate: new Date(Date.now() + 5 * 86_400_000).toISOString(),
      progress: 0,
    },
    {
      id: 'task-3',
      title: 'Validate builder reputation scores',
      status: 'completed',
      priority: 'low',
      assignee: 'QA Team',
      dueDate: new Date(Date.now() - 1 * 86_400_000).toISOString(),
      progress: 100,
    },
    {
      id: 'task-4',
      title: 'Fix locality normalization edge cases',
      status: 'blocked',
      priority: 'high',
      assignee: 'Backend',
      dueDate: new Date(Date.now() + 1 * 86_400_000).toISOString(),
      progress: 30,
    },
  ],
  insights: [
    {
      id: 'ins-1',
      title: 'Baner outperforming Wakad',
      description: 'Baner shows 12% higher appreciation with stronger builder sentiment.',
      impact: 'positive',
      metric: '+12.4%',
    },
    {
      id: 'ins-2',
      title: 'Rental demand spike in Whitefield',
      description: 'Search interest up 28% QoQ near IT corridor locations.',
      impact: 'positive',
      metric: '+28%',
    },
    {
      id: 'ins-3',
      title: 'Construction delay risk — Project Orion',
      description: 'Multiple negative reviews citing timeline slippage.',
      impact: 'negative',
      metric: '-15 sentiment',
    },
  ],
  properties: [
    {
      id: 'prop-001',
      title: '2 BHK Apartment — Green Heights',
      locality: 'Hinjewadi',
      city: 'Pune',
      bhk: 2,
      price: 78_00_000,
      area: 850,
      status: 'ready',
      source: 'Housing.com',
      builder: 'ABC Developers',
      sentiment: 82,
      trend: 'up',
      listedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-002',
      title: '3 BHK Flat — Skyline Residency',
      locality: 'Wakad',
      city: 'Pune',
      bhk: 3,
      price: 1_15_00_000,
      area: 1200,
      status: 'under_construction',
      source: 'MagicBricks',
      builder: 'Skyline Group',
      sentiment: 71,
      trend: 'stable',
      listedAt: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-003',
      title: '2 BHK — Urban Nest',
      locality: 'Baner',
      city: 'Pune',
      bhk: 2,
      price: 95_00_000,
      area: 920,
      status: 'ready',
      source: 'NoBroker',
      builder: 'Urban Corp',
      sentiment: 88,
      trend: 'up',
      listedAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-004',
      title: '1 BHK — Tech Park View',
      locality: 'Whitefield',
      city: 'Bangalore',
      bhk: 1,
      price: 42_00_000,
      area: 580,
      status: 'resale',
      source: 'Housing.com',
      builder: 'Private Owner',
      sentiment: 65,
      trend: 'down',
      listedAt: new Date(Date.now() - 8 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-005',
      title: '3 BHK — Lakeview Towers',
      locality: 'Kharadi',
      city: 'Pune',
      bhk: 3,
      price: 1_28_00_000,
      area: 1350,
      status: 'ready',
      source: 'MagicBricks',
      builder: 'Lakeview Builders',
      sentiment: 79,
      trend: 'up',
      listedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-006',
      title: '2 BHK — Metro Heights',
      locality: 'Electronic City',
      city: 'Bangalore',
      bhk: 2,
      price: 68_00_000,
      area: 780,
      status: 'under_construction',
      source: 'NoBroker',
      builder: 'Metro Infra',
      sentiment: 74,
      trend: 'stable',
      listedAt: new Date(Date.now() - 10 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-007',
      title: '4 BHK Penthouse — Elite Homes',
      locality: 'Baner',
      city: 'Pune',
      bhk: 4,
      price: 2_45_00_000,
      area: 2100,
      status: 'ready',
      source: 'Housing.com',
      builder: 'Elite Developers',
      sentiment: 91,
      trend: 'up',
      listedAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
    },
    {
      id: 'prop-008',
      title: '2 BHK — Garden View',
      locality: 'Hinjewadi',
      city: 'Pune',
      bhk: 2,
      price: 72_00_000,
      area: 810,
      status: 'resale',
      source: 'MagicBricks',
      builder: 'Private Owner',
      sentiment: 68,
      trend: 'down',
      listedAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      title: 'New match found',
      message: '3 properties match your Hinjewadi requirement.',
      timestamp: new Date(Date.now() - 10 * 60_000).toISOString(),
      read: false,
      type: 'success',
    },
    {
      id: 'notif-2',
      title: 'Price alert',
      message: 'Skyline Residency dropped by ₹2.5L.',
      timestamp: new Date(Date.now() - 1 * 3_600_000).toISOString(),
      read: false,
      type: 'info',
    },
    {
      id: 'notif-3',
      title: 'Sentiment warning',
      message: 'Negative trend detected for Wakad locality.',
      timestamp: new Date(Date.now() - 5 * 3_600_000).toISOString(),
      read: true,
      type: 'warning',
    },
    {
      id: 'notif-4',
      title: 'Report ready',
      message: 'Your Q2 investment analysis is available.',
      timestamp: new Date(Date.now() - 24 * 3_600_000).toISOString(),
      read: true,
      type: 'info',
    },
  ],
}
