import type { PropertyListing } from '@/types'

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

export const sampleProperties: PropertyListing[] = [
  {
    id: 'prop-001',
    title: 'Spacious 2 BHK with Garden View',
    description: 'Modern apartment with premium finishes, clubhouse access, and landscaped gardens.',
    image: img('photo-1502672260266-1c1ef2d93688'),
    images: [img('photo-1502672260266-1c1ef2d93688'), img('photo-1560448204-e02f11c3d0e2')],
    locality: 'Baner',
    city: 'Pune',
    bhk: 2,
    price: 95_00_000,
    area: 920,
    propertyType: 'apartment',
    furnishing: 'semi_furnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Gym', 'Pool', 'Security'],
    availability: 'available',
    rating: 4.6,
    reviewCount: 128,
    builder: 'Elite Developers',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 88,
    trend: 'up',
    listedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    isFeatured: true,
  },
  {
    id: 'prop-002',
    title: 'Luxury 3 BHK Penthouse',
    description: 'Panoramic city views, private terrace, and smart home automation.',
    image: img('photo-1613490493576-7fde63acd811'),
    images: [img('photo-1613490493576-7fde63acd811')],
    locality: 'Baner',
    city: 'Pune',
    bhk: 3,
    price: 2_45_00_000,
    area: 1850,
    propertyType: 'penthouse',
    furnishing: 'furnished',
    transactionType: 'buy',
    amenities: ['Terrace', 'Smart Home', 'Concierge', 'Pool', 'Gym'],
    availability: 'available',
    rating: 4.9,
    reviewCount: 64,
    builder: 'Prestige Group',
    status: 'ready',
    source: 'MagicBricks',
    sentiment: 94,
    trend: 'up',
    listedAt: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    isLuxury: true,
    isFeatured: true,
  },
  {
    id: 'prop-003',
    title: '2 BHK Near IT Park — Hinjewadi',
    description: 'Ideal for working professionals. 10 min drive to Rajiv Gandhi Infotech Park.',
    image: img('photo-1522708323590-d24dbb6b0267'),
    images: [img('photo-1522708323590-d24dbb6b0267')],
    locality: 'Hinjewadi',
    city: 'Pune',
    bhk: 2,
    price: 78_00_000,
    area: 850,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Power Backup', 'Lift', 'Security'],
    availability: 'available',
    rating: 4.3,
    reviewCount: 89,
    builder: 'ABC Developers',
    status: 'ready',
    source: 'NoBroker',
    sentiment: 82,
    trend: 'up',
    listedAt: new Date(Date.now() - 1 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-004',
    title: 'Furnished 2 BHK for Rent — Whitefield',
    description: 'Fully furnished flat with modular kitchen, near ITPL and metro.',
    image: img('photo-1564013799919-ab600027ffc6'),
    images: [img('photo-1564013799919-ab600027ffc6')],
    locality: 'Whitefield',
    city: 'Bangalore',
    bhk: 2,
    price: 35_000,
    area: 780,
    propertyType: 'apartment',
    furnishing: 'furnished',
    transactionType: 'rent',
    amenities: ['WiFi', 'Modular Kitchen', 'Parking', 'Gym'],
    availability: 'available',
    rating: 4.5,
    reviewCount: 56,
    builder: 'Brigade Group',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 79,
    trend: 'stable',
    listedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-005',
    title: 'Budget 1 BHK — Wakad',
    description: 'Compact and affordable starter home in rapidly developing Wakad corridor.',
    image: img('photo-1484154218962-a197022b5858'),
    images: [img('photo-1484154218962-a197022b5858')],
    locality: 'Wakad',
    city: 'Pune',
    bhk: 1,
    price: 42_00_000,
    area: 520,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Lift', 'Security'],
    availability: 'available',
    rating: 4.0,
    reviewCount: 34,
    builder: 'Skyline Group',
    status: 'under_construction',
    source: 'MagicBricks',
    sentiment: 71,
    trend: 'stable',
    listedAt: new Date(Date.now() - 10 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-006',
    title: '4 BHK Independent Villa — Kharadi',
    description: 'Spacious villa with private garden, servant quarter, and 3-car parking.',
    image: img('photo-1600596542815-ffad4c1539a9'),
    images: [img('photo-1600596542815-ffad4c1539a9')],
    locality: 'Kharadi',
    city: 'Pune',
    bhk: 4,
    price: 3_20_00_000,
    area: 2800,
    propertyType: 'villa',
    furnishing: 'semi_furnished',
    transactionType: 'buy',
    amenities: ['Garden', 'Private Pool', 'Parking', 'Security', 'Clubhouse'],
    availability: 'available',
    rating: 4.8,
    reviewCount: 42,
    builder: 'Lakeview Builders',
    status: 'ready',
    source: 'NoBroker',
    sentiment: 91,
    trend: 'up',
    listedAt: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    isLuxury: true,
  },
  {
    id: 'prop-007',
    title: '3 BHK Lake View — Baner',
    description: 'Premium lake-facing apartment with world-class amenities.',
    image: img('photo-1600585154340-be6161a56a0c'),
    images: [img('photo-1600585154340-be6161a56a0c')],
    locality: 'Baner',
    city: 'Pune',
    bhk: 3,
    price: 1_35_00_000,
    area: 1280,
    propertyType: 'apartment',
    furnishing: 'furnished',
    transactionType: 'buy',
    amenities: ['Lake View', 'Clubhouse', 'Pool', 'Gym', 'Jogging Track'],
    availability: 'under_offer',
    rating: 4.7,
    reviewCount: 97,
    builder: 'Urban Corp',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 86,
    trend: 'up',
    listedAt: new Date(Date.now() - 4 * 86_400_000).toISOString(),
    isFeatured: true,
  },
  {
    id: 'prop-008',
    title: 'Studio Apartment — Electronic City',
    description: 'Compact studio perfect for singles, near tech parks and metro.',
    image: img('photo-1505843513577-37664f580b27'),
    images: [img('photo-1505843513577-37664f580b27')],
    locality: 'Electronic City',
    city: 'Bangalore',
    bhk: 1,
    price: 18_000,
    area: 380,
    propertyType: 'studio',
    furnishing: 'furnished',
    transactionType: 'rent',
    amenities: ['WiFi', 'Housekeeping', 'Gym', 'Cafeteria'],
    availability: 'available',
    rating: 4.2,
    reviewCount: 28,
    builder: 'Metro Infra',
    status: 'ready',
    source: 'MagicBricks',
    sentiment: 74,
    trend: 'stable',
    listedAt: new Date(Date.now() - 6 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-009',
    title: '2 BHK Resale — Hinjewadi',
    description: 'Well-maintained resale flat in gated community with excellent connectivity.',
    image: img('photo-1600047509800-ba47f6869d8c'),
    images: [img('photo-1600047509800-ba47f6869d8c')],
    locality: 'Hinjewadi',
    city: 'Pune',
    bhk: 2,
    price: 72_00_000,
    area: 810,
    propertyType: 'apartment',
    furnishing: 'semi_furnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Garden', 'Security', 'Clubhouse'],
    availability: 'available',
    rating: 4.1,
    reviewCount: 45,
    builder: 'Private Owner',
    status: 'resale',
    source: 'NoBroker',
    sentiment: 68,
    trend: 'down',
    listedAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-010',
    title: 'Luxury 3 BHK — Bandra West',
    description: 'Sea-facing luxury apartment in Mumbai\'s most coveted neighborhood.',
    image: img('photo-1600607687939-ce8a6c25118c'),
    images: [img('photo-1600607687939-ce8a6c25118c')],
    locality: 'Bandra West',
    city: 'Mumbai',
    bhk: 3,
    price: 4_50_00_000,
    area: 1650,
    propertyType: 'apartment',
    furnishing: 'furnished',
    transactionType: 'buy',
    amenities: ['Sea View', 'Concierge', 'Spa', 'Pool', 'Valet Parking'],
    availability: 'available',
    rating: 4.9,
    reviewCount: 112,
    builder: 'Lodha Group',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 95,
    trend: 'up',
    listedAt: new Date(Date.now() - 8 * 86_400_000).toISOString(),
    isLuxury: true,
    isFeatured: true,
  },
  {
    id: 'prop-011',
    title: '3 BHK Under Construction — Wakad',
    description: 'New launch with early-bird pricing. Possession in 18 months.',
    image: img('photo-1600566753190-17f0baa2a6c3'),
    images: [img('photo-1600566753190-17f0baa2a6c3')],
    locality: 'Wakad',
    city: 'Pune',
    bhk: 3,
    price: 1_15_00_000,
    area: 1200,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    transactionType: 'buy',
    amenities: ['Clubhouse', 'Pool', 'Kids Play Area', 'Jogging Track'],
    availability: 'available',
    rating: 4.4,
    reviewCount: 67,
    builder: 'Skyline Group',
    status: 'under_construction',
    source: 'MagicBricks',
    sentiment: 76,
    trend: 'up',
    listedAt: new Date(Date.now() - 15 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-012',
    title: 'Affordable 2 BHK — Kharadi',
    description: 'Value-for-money apartment near EON IT Park with good rental yield.',
    image: img('photo-1600573472592-401b489a3cdc'),
    images: [img('photo-1600573472592-401b489a3cdc')],
    locality: 'Kharadi',
    city: 'Pune',
    bhk: 2,
    price: 58_00_000,
    area: 720,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Lift', 'Security', 'Power Backup'],
    availability: 'sold',
    rating: 4.0,
    reviewCount: 23,
    builder: 'Kolte Patil',
    status: 'ready',
    source: 'NoBroker',
    sentiment: 72,
    trend: 'stable',
    listedAt: new Date(Date.now() - 20 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-013',
    title: 'Furnished 3 BHK — Hinjewadi',
    description: 'Move-in ready furnished home near major IT campuses.',
    image: img('photo-1600210492490-0250575c0909'),
    images: [img('photo-1600210492490-0250575c0909')],
    locality: 'Hinjewadi',
    city: 'Pune',
    bhk: 3,
    price: 55_000,
    area: 1150,
    propertyType: 'apartment',
    furnishing: 'furnished',
    transactionType: 'rent',
    amenities: ['Modular Kitchen', 'WiFi', 'Parking', 'Gym', 'Pool'],
    availability: 'available',
    rating: 4.6,
    reviewCount: 38,
    builder: 'Green Heights',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 84,
    trend: 'up',
    listedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-014',
    title: '5 BHK Luxury Villa — Lonavala',
    description: 'Weekend retreat villa with mountain views and private pool.',
    image: img('photo-1613977257363-707ba934c7d8'),
    images: [img('photo-1613977257363-707ba934c7d8')],
    locality: 'Lonavala',
    city: 'Pune',
    bhk: 5,
    price: 5_50_00_000,
    area: 4200,
    propertyType: 'villa',
    furnishing: 'furnished',
    transactionType: 'buy',
    amenities: ['Private Pool', 'Mountain View', 'Garden', 'BBQ Area', 'Home Theatre'],
    availability: 'available',
    rating: 4.9,
    reviewCount: 19,
    builder: 'Hillscape Estates',
    status: 'ready',
    source: 'MagicBricks',
    sentiment: 92,
    trend: 'up',
    listedAt: new Date(Date.now() - 30 * 86_400_000).toISOString(),
    isLuxury: true,
  },
  {
    id: 'prop-015',
    title: '2 BHK Gated Community — Baner',
    description: 'Secure gated community with 24/7 security and landscaped parks.',
    image: img('photo-1600585154526-990dced4db0d'),
    images: [img('photo-1600585154526-990dced4db0d')],
    locality: 'Baner',
    city: 'Pune',
    bhk: 2,
    price: 88_00_000,
    area: 890,
    propertyType: 'apartment',
    furnishing: 'semi_furnished',
    transactionType: 'buy',
    amenities: ['Gated Community', 'Park', 'Gym', 'Pool', 'Security'],
    availability: 'available',
    rating: 4.5,
    reviewCount: 76,
    builder: 'Paranjape Schemes',
    status: 'ready',
    source: 'NoBroker',
    sentiment: 85,
    trend: 'up',
    listedAt: new Date(Date.now() - 9 * 86_400_000).toISOString(),
  },
  {
    id: 'prop-016',
    title: '1 BHK Budget Flat — Wakad',
    description: 'Starter home for young professionals at an unbeatable price point.',
    image: img('photo-1600607687644-c7171b42498f'),
    images: [img('photo-1600607687644-c7171b42498f')],
    locality: 'Wakad',
    city: 'Pune',
    bhk: 1,
    price: 38_00_000,
    area: 480,
    propertyType: 'apartment',
    furnishing: 'unfurnished',
    transactionType: 'buy',
    amenities: ['Parking', 'Lift', 'Security'],
    availability: 'available',
    rating: 3.9,
    reviewCount: 18,
    builder: 'Budget Homes',
    status: 'ready',
    source: 'Housing.com',
    sentiment: 65,
    trend: 'stable',
    listedAt: new Date(Date.now() - 14 * 86_400_000).toISOString(),
  },
]

export const trendingLocations = [
  { name: 'Baner', count: 42, growth: 12.4 },
  { name: 'Hinjewadi', count: 38, growth: 8.6 },
  { name: 'Whitefield', count: 31, growth: 15.2 },
  { name: 'Wakad', count: 27, growth: 5.8 },
  { name: 'Kharadi', count: 24, growth: 9.1 },
]

export const propertyCategories = [
  { type: 'Apartments', count: 68, icon: 'Building2' },
  { type: 'Villas', count: 14, icon: 'Home' },
  { type: 'Luxury', count: 22, icon: 'Sparkles' },
  { type: 'Budget', count: 35, icon: 'Wallet' },
  { type: 'For Rent', count: 28, icon: 'Key' },
]

export const localities = [...new Set(sampleProperties.map((p) => p.locality))].sort()
